name: Daily Run of automate.py

on:
  push:
    branches:
      - main
  schedule:
    # Runs the workflow daily at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  Run-Python-Script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.14.0-alpha.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0-alpha.2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade Pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run automate.py
        run: python automate.py

      # Step 5: Post-run status
      - run: echo "🍏 The script execution completed with status ${{ job.status }}."
